In [2]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

Wall time: 1.37 s


In [3]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += 1
    return ans

arr = range(10**7)
print(summ(arr))

10000000
Wall time: 513 ms


In [4]:
import numpy as np

In [5]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), print(type(a)))

<class 'list'>
<class 'numpy.ndarray'> None


In [6]:
b

array([1., 2., 3.])

In [7]:
a = [1, 2, 'a']
b = np.array(a)
print('Для list:', type(a[0]),
      '\nДля np.array:', type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [8]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [9]:
type(d)

numpy.ndarray

In [10]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',


In [11]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [12]:
arr.nbytes

20

In [13]:
np.lookfor('mean value of array')

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.matrix.partition
    R

In [14]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x000001EF95FA1670>
File:            c:\programdata\anaconda3\lib\site-packages\numpy\ma\core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average: Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of the method to transform.


In [15]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

In [16]:
arr = np.array([[[1, 2, 3, 4],
                 [2, 3, 4, 3],
                 [1, 1, 1, 1]],
                [[1, 2, 3, 4],
                 [2, 3, 4, 3],
                 [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [17]:
print('len:', len(arr), '-- количество элементов по первой оси.',
      '\nsize:', arr.size, '-- всего элементов в матрице.',
      '\nndim:', arr.ndim, '-- размерность матрицы.',
      '\nshape:', arr.shape, '-- количество элементов по каждой оси.')

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


In [18]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

In [19]:
a[-1]

4

In [20]:
a[2] = -1
a

array([ 1,  2, -1,  4])

In [21]:
for i in a:
    print(i)

1
2
-1
4


In [22]:
arr = np.array([2, 3, 5, 7])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

[2 3 5 7]
int32
<class 'numpy.ndarray'>
(4,)
16


In [23]:
a = np.zeros(7)
b = np.ones(7, dtype=np.int16)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


In [24]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [25]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [26]:
a = np.arange(1, 16, 4)
b = np.arange(5, 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5  7  9 11 13 15 17 19]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [32]:
a = np.linspace(1, 15, 2)
b = np.linspace(6, 15, 10)
print(a)
print(b)

[ 1. 15.]
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [34]:
a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


In [35]:
b = np.logspace(0, 3, 12)
print(b)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


In [36]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)

print(a)
print(b)
print('\n\n')

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


In [37]:
print(5 * a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [38]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [39]:
print(a + np.arange(11, dtype='int16'))
print(type(a[0]))

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
<class 'numpy.float64'>


In [40]:
type(np.cos)

numpy.ufunc

In [41]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [42]:
np.log(b)

<ipython-input-42-3f8f764f67ee>:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [43]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [50]:
c = np.arange(0., 20)
print(type(c[0]))

<class 'numpy.float64'>


In [51]:
np.any(c == 0.), np.all(c != 0)


(True, False)

In [52]:
c += np.sin(4)
print(c)

[-0.7568025  0.2431975  1.2431975  2.2431975  3.2431975  4.2431975
  5.2431975  6.2431975  7.2431975  8.2431975  9.2431975 10.2431975
 11.2431975 12.2431975 13.2431975 14.2431975 15.2431975 16.2431975
 17.2431975 18.2431975]


In [53]:
c *= 2
print(c)

[-1.51360499  0.48639501  2.48639501  4.48639501  6.48639501  8.48639501
 10.48639501 12.48639501 14.48639501 16.48639501 18.48639501 20.48639501
 22.48639501 24.48639501 26.48639501 28.48639501 30.48639501 32.48639501
 34.48639501 36.48639501]


In [54]:
b = np.arange(1., 21, 1)
d = (b + c)
d /= b
print(d)

[-0.51360499  1.2431975   1.82879834  2.12159875  2.297279    2.41439917
  2.49805643  2.56079938  2.60959945  2.6486395   2.68058136  2.70719958
  2.72972269  2.74902821  2.76575967  2.78039969  2.79331735  2.80479972
  2.81507342  2.82431975]


In [55]:
print(np.array([0.0, 0.0, 10., -1.0,]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


<ipython-input-55-20301f651ecd>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([0.0, 0.0, 10., -1.0,]) / np.array([1.0, 0.0, 0.0, 0.0]))
<ipython-input-55-20301f651ecd>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0.0, 0.0, 10., -1.0,]) / np.array([1.0, 0.0, 0.0, 0.0]))


In [56]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [57]:
print(b)
print(b.cumsum())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91. 105.
 120. 136. 153. 171. 190. 210.]


In [59]:
a = np.array([1, 5, 6, 10, -2, 0, 10])
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 10]
[ 1  5  6 10 -2  0 10]


In [60]:
a.sort()
print(a)

[-2  0  1  5  6 10 10]


In [61]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [62]:
c = np.hstack((a, b, 5*b))
c

array([-2.,  0.,  1.,  5.,  6., 10., 10.,  1.,  1.,  1.,  1.,  1.,  5.,
        5.,  5.,  5.,  5.])

In [63]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[-2  0  1  5  6 10 10]
[-2  0  1]
[5 6]
[10]
[10]


In [64]:
print(np.delete(a, [2, 4, 1]))
print(a)

[-2  5 10 10]
[-2  0  1  5  6 10 10]


In [67]:
np.insert(a, 2, [-1, -1])

array([-2,  0, -1, -1,  1,  5,  6, 10, 10])

In [68]:
np.append(a, [2.2, 2.1])

array([-2. ,  0. ,  1. ,  5. ,  6. , 10. , 10. ,  2.2,  2.1])

In [69]:
a[::-1]

array([10, 10,  6,  5,  1,  0, -2])

In [70]:
print(a)

[-2  0  1  5  6 10 10]


In [71]:
a[2:5]

array([1, 5, 6])

In [72]:
b = a[0:6]
b[1] = -1000
print(a)

[   -2 -1000     1     5     6    10    10]


In [73]:
b = a[0:4:2]
print(b)

a[1:6:3] = 0
print(a)

[-2  1]
[-2  0  1  5  0 10 10]


In [74]:
b = a.copy()
b[2] = -4
print(b)
print(a)

[-2  0 -4  5  0 10 10]
[-2  0  1  5  0 10 10]


In [75]:
print(a[[5,3,1]])

[10  5  0]


In [81]:
a = np.linspace(-4*np.pi, 4*np.pi, 100)
b = (np.sin(a) ** 2 + np.cos(a) ** 2).round()
np.all(b == 1)