In [1]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

Wall time: 1.41 s


In [2]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += 1
    return ans

arr = range(10**7)
print(summ(arr))

10000000
Wall time: 492 ms


In [4]:
import numpy as np

In [5]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), print(type(a)))

<class 'list'>
<class 'numpy.ndarray'> None


In [6]:
b

array([1., 2., 3.])

In [7]:
a = [1, 2, 'a']
b = np.array(a)
print('Для list:', type(a[0]),
      '\nДля np.array:', type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [8]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [9]:
type(d)

numpy.ndarray

In [10]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',


In [11]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [12]:
arr.nbytes

20

In [13]:
np.lookfor('mean value of array')

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.matrix.partition
    R

In [14]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x000001DF0031C550>
File:            c:\programdata\anaconda3\lib\site-packages\numpy\ma\core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average: Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of the method to transform.


In [15]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

In [20]:
arr = np.array([[[1, 2, 3, 4],
                 [2, 3, 4, 3],
                 [1, 1, 1, 1]],
                [[1, 2, 3, 4],
                 [2, 3, 4, 3],
                 [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [21]:
print('len:', len(arr), '-- количество элементов по первой оси.',
      '\nsize:', arr.size, '-- всего элементов в матрице.',
      '\nndim:', arr.ndim, '-- размерность матрицы.',
      '\nshape:', arr.shape, '-- количество элементов по каждой оси.')

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


In [22]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

In [23]:
a[-1]

4

In [24]:
a[2] = -1
a

array([ 1,  2, -1,  4])