In [3]:
#!pip install torch
import torch

In [4]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

In [5]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [6]:
a.shape

torch.Size([2])

In [7]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
b.shape

torch.Size([2, 3])

In [9]:
x = torch.FloatTensor(2,3,4)
x

tensor([[[9.1837e-39, 4.6837e-39, 9.9184e-39, 9.0000e-39],
         [1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39],
         [9.8265e-39, 9.4592e-39, 1.0561e-38, 1.0653e-38]],

        [[1.0469e-38, 9.5510e-39, 1.0745e-38, 9.6429e-39],
         [1.0561e-38, 9.1837e-39, 1.0653e-38, 8.4490e-39],
         [1.0745e-38, 9.6429e-39, 1.0561e-38, 9.0918e-39]]])

In [10]:
x = torch.FloatTensor(100)
x

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3079e+20,
        2.6302e+20, 6.1943e-04, 7.2056e+22, 2.1720e+29, 1.8057e+28, 5.1412e+31,
        7.5338e+28, 6.1687e+16, 2.5353e-09, 5.4071e+22, 2.6318e-12, 2.5958e-06,
        5.4071e+22, 2.6318e-12, 1.6615e-04, 5.3191e+22, 2.6318e-12, 6.3382e-10,
        5.2002e+22, 8.3407e+17, 2.0190e-19, 1.3563e-19, 1.3563e-19, 6.3371e-10,
        5.2304e+22, 2.6176e-12, 6.3371e-10, 5.2893e+22, 2.6176e-12, 2.5350e-09,
        5.4070e+22, 2.6318e-12, 1.6615e-04, 5.2601e+22, 8.3407e+17, 2.0190e-19,
        1.3563e-19, 1.3563e-19, 4.1538e-05, 5.3484e+22, 2.6318e-12, 1.6226e-07,
        5.2602e+22, 2.6318e-12, 6.3371e-10, 5.2304e+22, 2.6176e-12, 6.3371e-10,
        5.2893e+22, 8.2956e+17, 1.7035e+28, 1.3589e-19, 1.3563e-19, 6.1678e+16,
        1.6408e-07, 1.3030e-11, 1.4588e-19, 6.7495e-07, 1.3028e-11, 1.4588e-19,
        1.0501e-05, 1.3029e-11, 1.4588e-19, 1.6967e-07, 1.3030e-11, 3.1438e-12,
        1.3589e-19, 1.3563e-19, 4.5071e+

In [11]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

In [12]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[ 574235236,  825372722,  758133037,  810824752],
         [ 909130297,  775303482,  876164662,  576337200]],

        [[1701061164, 1684956528, 1768124005, 1834972005],
         [ 975336549, 1702195828, 1852121644, 1701734759]],

        [[ 874658338,  842622565,  761673316, 1717778488],
         [ 878916653,  862072119,  841834800,  825386594]]], dtype=torch.int32)

In [14]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x2, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])