In [1]:
#!pip install torch
import torch

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

In [3]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [4]:
a.shape

torch.Size([2])

In [5]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.shape

torch.Size([2, 3])

In [7]:
x = torch.FloatTensor(2,3,4)
x

tensor([[[7.1843e+22, 1.0302e+21, 4.7742e+33, 1.2681e-14],
         [1.8888e+31, 7.5769e+23, 1.6457e+19, 3.0263e+29],
         [1.4607e-19, 1.8888e+31, 1.2712e+31, 3.2745e-12]],

        [[1.7743e+28, 2.0535e-19, 1.1022e+24, 1.4607e-19],
         [6.8801e+16, 6.9397e+22, 1.1095e+27, 3.0304e+35],
         [1.2102e+25, 9.8834e+17, 4.8418e+30, 3.2599e-12]]])

In [8]:
x = torch.FloatTensor(100)
x

tensor([ 3.9115e-28,  6.1097e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44,
         0.0000e+00,  9.8091e-45,  0.0000e+00,  2.5223e-26,  6.1097e-43,
        -8.9169e-09,  5.2632e+24,  0.0000e+00,  0.0000e+00,  2.1019e-44,
         0.0000e+00,  1.2590e+01,  1.7905e+28,  2.8181e+20,  9.2199e-39,
         0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00,  9.8091e-45,
         0.0000e+00,  2.5222e-26,  6.1097e-43,  2.2075e-01, -9.0717e+25,
         0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00,  1.1258e+24,
         1.0454e+12,  1.0131e-28,  6.1097e-43,  0.0000e+00,  0.0000e+00,
         2.1019e-44,  0.0000e+00,  9.8091e-45,  0.0000e+00,  2.5225e-26,
         6.1097e-43,  1.7853e-14,  2.1792e-04,  0.0000e+00,  0.0000e+00,
         2.1019e-44,  0.0000e+00,  1.1258e+24,  2.5523e+08,  1.0137e-38,
         6.1097e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00,
         9.8091e-45,  0.0000e+00,  2.5226e-26,  6.1097e-43,  3.4317e+31,
        -6.6171e-34,  0.0000e+00,  0.0000e+00,  2.1

In [9]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

In [10]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[ 859126324,  775303738,  876163124,  576336179],
         [1701061164, 1684956528, 1768124005, 1834972005]],

        [[ 975336549, 1702195828, 1852121644, 1701734759],
         [ 941767202, 1714762337,  758198579, 1701142882]],

        [[ 878851117,  892939574,  942499122,  926114361],
         [ 943143268,  576926818, 1953702444, 1937077345]]], dtype=torch.int32)

In [11]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x2, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
x = torch.randn((2,3))                # Normal(0, 1) with shape
x

tensor([[-0.7851,  0.0459,  0.5579],
        [ 2.2601,  1.4226,  0.0515]])

In [13]:
x.random_(0, 10)                      # discrete U[0, 10]
x.uniform_(0, 1)                      # U[0, 1]
x.normal_(mean=0, std=1)              # Normal with mean and std
x.bernoulli_(p=0.5)                   # bernoulli with parameter p

tensor([[1., 0., 0.],
        [0., 0., 0.]])

In [14]:
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [15]:
b.view(3, 2), b.view(3, 2).stride()

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

In [16]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [17]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
b.T.stride(), b.is_contiguous(), b.T.is_contiguous()

((1, 3), True, False)

In [19]:
b.reshape(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [20]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [22]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [23]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [24]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [25]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

In [26]:
a

tensor([ 1.5000,  3.2000, -7.0000])

In [27]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [28]:
a[0, 0]

tensor(100.)

In [29]:
a[0:2, 0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

In [30]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [-100, -200, -300]])

In [31]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
a.add(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [33]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [34]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [35]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [36]:
a.sub_(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [37]:
a * b

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [38]:
a.mul(b)

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [39]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [-100, -200, -300]])

In [40]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [41]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [42]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [43]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [44]:
a != b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [45]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [46]:
a > b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [47]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [48]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [49]:
b[a == b]

tensor([100., 200., 300.])

In [50]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [51]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [52]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [53]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [54]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [55]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [56]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [57]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [58]:
a.mean()

tensor(74.)

In [59]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [60]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [61]:
a.sum(1)

tensor([  6.,  60., 600.])

In [62]:
a.max()

tensor(300.)

In [63]:
a.max(0)

torch.return_types.max(
values=tensor([100., 200., 300.]),
indices=tensor([2, 2, 2]))

In [64]:
a.min()

tensor(1.)

In [65]:
a.min(0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

In [66]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [67]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [68]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [69]:
a.dot(b)

tensor(-141.)

In [70]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [71]:
a @ b

tensor(-141.)

In [72]:
type(a)

torch.Tensor

In [73]:
type(b)

torch.Tensor

In [74]:
type(a @ b)

torch.Tensor

In [75]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [76]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [77]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [78]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [79]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [80]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

In [81]:
b.view(-1)

tensor([ -1., -10., 100.])

In [82]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [83]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [84]:
y = torch.Tensor(2, 3, 4, 5)
z = torch.Tensor(2, 3, 5, 6)
(y @ z).shape

torch.Size([2, 3, 4, 6])

In [85]:
import numpy as np

In [86]:
a = np.random.rand(3, 3)
a

array([[0.12559095, 0.49465733, 0.25301963],
       [0.11487327, 0.40026965, 0.982412  ],
       [0.33634083, 0.46048894, 0.94111533]])

In [87]:
b = torch.from_numpy(a)
b

tensor([[0.1256, 0.4947, 0.2530],
        [0.1149, 0.4003, 0.9824],
        [0.3363, 0.4605, 0.9411]], dtype=torch.float64)

In [88]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [89]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22],
         [2.5226e-18, 2.5930e-09, 1.0015e-11, 3.0881e-09]],

        [[4.2195e-08, 4.2109e-11, 2.6662e-09, 2.9574e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]]])

In [91]:
type(a)

torch.Tensor

In [92]:
x = a.numpy()
x

array([[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 7.7052459e+31, 7.2147959e+22],
        [2.5225907e-18, 2.5929805e-09, 1.0015361e-11, 3.0881431e-09]],

       [[4.2195282e-08, 4.2108740e-11, 2.6661957e-09, 2.9574267e-18],
        [6.7333120e+22, 1.7590538e+22, 1.7184218e+25, 4.3221663e+27],
        [6.1971537e-04, 7.2443192e+22, 1.7728345e+28, 7.0366722e+22]]],
      dtype=float32)

In [93]:
x.shape

(2, 3, 4)

In [94]:
type(x)

numpy.ndarray

In [95]:
x -= x

In [96]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [97]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [98]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print(f'result: {result}')

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


In [99]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.0231, 0.8724, 0.4728,  ..., 0.0373, 0.2747, 0.1259],
        [0.6855, 0.1308, 0.6894,  ..., 0.1703, 0.0358, 0.1327],
        [0.6926, 0.8926, 0.3277,  ..., 0.3492, 0.6964, 0.6940],
        ...,
        [0.7111, 0.5877, 0.2845,  ..., 0.1660, 0.9738, 0.1171],
        [0.9669, 0.7990, 0.4998,  ..., 0.4444, 0.4612, 0.9539],
        [0.8824, 0.4450, 0.3428,  ..., 0.9119, 0.0290, 0.7732]])

In [100]:
x.is_cuda

False

In [101]:
!nvidia-smi

Thu Oct  7 20:53:30 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8     2W /  N/A |    319MiB /  4096MiB |     34%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [102]:
x = x.cuda()

In [103]:
!nvidia-smi

Thu Oct  7 20:53:33 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0    14W /  N/A |    886MiB /  4096MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [104]:
x

tensor([[0.0231, 0.8724, 0.4728,  ..., 0.0373, 0.2747, 0.1259],
        [0.6855, 0.1308, 0.6894,  ..., 0.1703, 0.0358, 0.1327],
        [0.6926, 0.8926, 0.3277,  ..., 0.3492, 0.6964, 0.6940],
        ...,
        [0.7111, 0.5877, 0.2845,  ..., 0.1660, 0.9738, 0.1171],
        [0.9669, 0.7990, 0.4998,  ..., 0.4444, 0.4612, 0.9539],
        [0.8824, 0.4450, 0.3428,  ..., 0.9119, 0.0290, 0.7732]],
       device='cuda:0')

In [105]:
x = x.cpu()
!nvidia-smi

torch.cuda.empty_cache()
!nvidia-smi

Thu Oct  7 20:53:33 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0    15W /  N/A |    888MiB /  4096MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [106]:
device = torch.device('cuda:0')
x = x.to(device)
x

tensor([[0.0231, 0.8724, 0.4728,  ..., 0.0373, 0.2747, 0.1259],
        [0.6855, 0.1308, 0.6894,  ..., 0.1703, 0.0358, 0.1327],
        [0.6926, 0.8926, 0.3277,  ..., 0.3492, 0.6964, 0.6940],
        ...,
        [0.7111, 0.5877, 0.2845,  ..., 0.1660, 0.9738, 0.1171],
        [0.9669, 0.7990, 0.4998,  ..., 0.4444, 0.4612, 0.9539],
        [0.8824, 0.4450, 0.3428,  ..., 0.9119, 0.0290, 0.7732]],
       device='cuda:0')

In [107]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [108]:
c

tensor([[7.0070e-02, 3.4874e-01, 7.1342e-02,  ..., 4.0125e-04, 1.4958e-01,
         2.1855e-01],
        [5.5181e-01, 6.8587e-02, 2.4001e-01,  ..., 1.4292e-02, 2.6833e-03,
         2.7711e-02],
        [4.5578e-01, 8.8373e-01, 6.3207e-01,  ..., 2.2839e-01, 1.5605e-01,
         1.5504e-01],
        ...,
        [1.7011e-01, 3.5981e-01, 4.7637e-01,  ..., 6.6385e-03, 5.7341e-02,
         4.0665e-01],
        [6.8999e-02, 1.5135e-01, 1.2949e-01,  ..., 9.9298e-03, 3.7470e-01,
         3.0967e-02],
        [7.0650e-01, 2.0691e-01, 7.0995e-01,  ..., 3.5127e-01, 6.1582e-02,
         1.6630e-01]])

In [109]:
a

tensor([[0.1840, 0.7289, 0.8247,  ..., 0.0012, 0.5861, 0.7388],
        [0.7161, 0.6381, 0.9748,  ..., 0.1678, 0.0103, 0.4975],
        [0.6923, 0.8862, 0.7361,  ..., 0.6279, 0.1931, 0.4881],
        ...,
        [0.2618, 0.8198, 0.9820,  ..., 0.3394, 0.1765, 0.4794],
        [0.1332, 0.4681, 0.1355,  ..., 0.1194, 0.5854, 0.6735],
        [0.7406, 0.5954, 0.7638,  ..., 0.7998, 0.6778, 0.4983]])

In [110]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [111]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.7029, 1.4577, 1.4687, 1.2542, 1.7966],
         [1.3314, 1.7450, 1.2424, 1.4790, 1.1573],
         [1.0903, 1.2275, 1.5324, 1.3933, 1.1356],
         [1.2173, 1.6436, 1.9200, 1.9229, 1.8441],
         [1.7121, 1.8983, 1.7519, 1.4793, 1.1460]],

        [[1.7603, 1.7828, 1.9773, 1.4672, 1.5324],
         [1.8157, 1.6339, 1.0316, 1.3168, 1.8242],
         [1.8976, 1.8352, 1.1854, 1.9083, 1.9871],
         [1.7152, 1.3665, 1.2983, 1.0780, 1.8988],
         [1.2590, 1.8672, 1.9267, 1.9990, 1.2938]],

        [[1.4265, 1.1154, 1.3758, 1.9262, 1.1527],
         [1.1788, 1.3869, 1.3321, 1.0264, 1.6885],
         [1.9481, 1.3442, 1.7684, 1.1867, 1.8316],
         [1.6579, 1.2103, 1.5039, 1.5331, 1.4941],
         [1.8005, 1.2728, 1.5213, 1.2348, 1.7665]],

        [[1.0194, 1.3880, 1.2191, 1.7113, 1.2874],
         [1.0290, 1.2446, 1.4407, 1.5352, 1.7752],
         [1.1177, 1.6781, 1.7602, 1.9543, 1.9780],
         [1.8566, 1.1298, 1.7811, 1.8570, 1.3040],
         [1.5178, 1.1719,

In [112]:
dtype = torch.float
device = torch.device('cuda:0')

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 3, 3, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

In [113]:
y_pred = (x @ w1).clamp(min=0).matmul(w2)
loss = (y_pred - y).pow(2).sum()
# calculate the gradients
loss.backward()

In [114]:
print((y_pred -y).pow(2).sum())

tensor(2892.9746, device='cuda:0', grad_fn=<SumBackward0>)


In [115]:
w1.grad, w2.grad

(tensor([[-565.5472, -767.7705,  853.5779],
         [ 981.4084, -104.8400,  -14.8326],
         [ 356.2612,  -50.6574, -439.1010]], device='cuda:0'),
 tensor([[  11.8501,  352.6769,  -94.6290,  140.2911,  129.5164,  189.5405,
            24.9894, -121.0933,  -46.2717,  -13.9303],
         [ 178.0907,  326.9442,  -46.0827,  -69.5456,  133.9215,  213.1326,
           121.8515, -383.5352,  -15.6206,  196.7343],
         [ -26.6786,   65.8424,  101.1710, -120.8757,  191.8034, -231.6657,
           150.4857,  -73.8392, -222.7654, -258.5098]], device='cuda:0'))

In [116]:
loss.grad # can't access to non-leaf grad in AD tree

<ipython-input-116-09a6243c8d35>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  loss.grad


In [119]:
y_pred = (x @ w1).clamp(min=0).matmul(w2)
y_pred.retain_grad()

loss = (y_pred - y).pow(2).sum()
loss.retain_grad()

loss.backward()

In [120]:
loss.grad

tensor(1., device='cuda:0')

In [117]:
x.grad # doesn't require grad

In [118]:
y.grad # doesn't require grad

In [121]:
w1

tensor([[-0.2979, -1.5464,  1.7638],
        [ 1.3745, -0.4132, -0.5322],
        [ 0.3828, -0.1081, -0.7653]], device='cuda:0', requires_grad=True)

In [122]:
with torch.no_grad():
    pass