In [2]:
#!pip install torch
import torch

In [3]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

In [4]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [5]:
a.shape

torch.Size([2])

In [6]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
b.shape

torch.Size([2, 3])

In [8]:
x = torch.FloatTensor(2,3,4)
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
x = torch.FloatTensor(100)
x

tensor([4.0058e-11, 1.6969e-07, 5.9651e-07, 4.2963e-05, 8.2990e-33, 1.3563e-19,
        1.3563e-19, 1.3563e-19, 4.0058e-11, 4.3677e-05, 6.2983e-10, 2.6255e-06,
        9.1048e-12, 2.6849e-06, 1.4588e-19, 4.0562e-08, 8.2956e+17, 6.6522e-33,
        1.3563e-19, 1.6114e-19, 4.4721e+21, 1.7241e+25, 3.1997e-12, 1.4601e-19,
        1.8990e+28, 1.1259e+24, 1.7667e+22, 5.3000e+31, 4.3988e+21, 1.1703e-19,
        5.0746e+31, 7.5338e+28, 6.1687e+16, 2.4754e-12, 4.1422e-11, 5.8253e-10,
        1.3567e-19, 3.1432e-12, 1.3563e-19, 1.3563e-19, 1.3563e-19, 5.8337e-10,
        9.1048e-12, 1.4584e-19, 2.4754e-12, 4.1411e-11, 1.1704e-19, 1.3563e-19,
        1.3563e-19, 4.5071e+16, 2.4754e-12, 4.0956e-11, 6.2983e-10, 1.3567e-19,
        3.1432e-12, 1.3563e-19, 1.3563e-19, 1.3563e-19, 6.3067e-10, 9.1048e-12,
        1.4584e-19, 2.4754e-12, 4.1411e-11, 8.1546e-33, 1.3563e-19, 1.8578e-01,
        4.7429e+30, 1.2869e+22, 1.9422e+20, 3.2134e-12, 3.0353e+32, 1.8058e+28,
        7.3463e+28, 2.6284e-15, 7.4098e+

In [10]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

In [11]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

In [12]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x2, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
x = torch.randn((2,3))                # Normal(0, 1) with shape
x

tensor([[ 1.0455, -0.8817,  2.3878],
        [ 0.3775, -0.7279,  0.7450]])

In [14]:
x.random_(0, 10)                      # discrete U[0, 10]
x.uniform_(0, 1)                      # U[0, 1]
x.normal_(mean=0, std=1)              # Normal with mean and std
x.bernoulli_(p=0.5)                   # bernoulli with parameter p

tensor([[0., 1., 0.],
        [1., 1., 1.]])

In [15]:
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [16]:
b.view(3, 2), b.view(3, 2).stride()

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

In [17]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [18]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
b.T.stride(), b.is_contiguous(), b.T.is_contiguous()

((1, 3), True, False)

In [20]:
b.reshape(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [21]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [23]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [24]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [25]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [26]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

In [27]:
a

tensor([ 1.5000,  3.2000, -7.0000])

In [28]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [29]:
a[0, 0]

tensor(100.)

In [30]:
a[0:2, 0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

In [31]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [-100, -200, -300]])

In [32]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [33]:
a.add(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [35]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [36]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [37]:
a.sub_(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [38]:
a * b

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [39]:
a.mul(b)

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [40]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [-100, -200, -300]])

In [41]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [42]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [43]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [44]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [45]:
a != b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [46]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [47]:
a > b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [48]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [49]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [50]:
b[a == b]

tensor([100., 200., 300.])

In [51]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [52]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [53]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [54]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [55]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [56]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [57]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [58]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [59]:
a.mean()

tensor(74.)

In [60]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [61]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [62]:
a.sum(1)

tensor([  6.,  60., 600.])

In [63]:
a.max()

tensor(300.)

In [64]:
a.max(0)

torch.return_types.max(
values=tensor([100., 200., 300.]),
indices=tensor([2, 2, 2]))

In [65]:
a.min()

tensor(1.)

In [66]:
a.min(0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

In [67]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [68]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [69]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [70]:
a.dot(b)

tensor(-141.)

In [71]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [72]:
a @ b

tensor(-141.)

In [73]:
type(a)

torch.Tensor

In [74]:
type(b)

torch.Tensor

In [75]:
type(a @ b)

torch.Tensor

In [76]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [77]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [78]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [79]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [80]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [81]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

In [82]:
b.view(-1)

tensor([ -1., -10., 100.])

In [83]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [84]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [85]:
y = torch.Tensor(2, 3, 4, 5)
z = torch.Tensor(2, 3, 5, 6)
(y @ z).shape

torch.Size([2, 3, 4, 6])

In [86]:
import numpy as np

In [87]:
a = np.random.rand(3, 3)
a

array([[0.26912477, 0.57276427, 0.8064215 ],
       [0.14508811, 0.87640034, 0.70035021],
       [0.82383319, 0.27280117, 0.18339492]])

In [88]:
b = torch.from_numpy(a)
b

tensor([[0.2691, 0.5728, 0.8064],
        [0.1451, 0.8764, 0.7004],
        [0.8238, 0.2728, 0.1834]], dtype=torch.float64)

In [89]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [90]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22],
         [2.5226e-18, 2.5930e-09, 1.0015e-11, 3.0881e-09]],

        [[4.1031e-08, 4.0518e-11, 4.4159e-05, 2.9574e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]]])

In [92]:
type(a)

torch.Tensor

In [93]:
x = a.numpy()
x

array([[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 7.7052459e+31, 7.2147959e+22],
        [2.5225907e-18, 2.5929805e-09, 1.0015361e-11, 3.0880862e-09]],

       [[4.1031136e-08, 4.0518013e-11, 4.4158842e-05, 2.9573729e-18],
        [6.7333120e+22, 1.7590538e+22, 1.7184218e+25, 4.3221663e+27],
        [6.1971537e-04, 7.2443192e+22, 1.7728345e+28, 7.0366722e+22]]],
      dtype=float32)

In [94]:
x.shape

(2, 3, 4)

In [95]:
type(x)

numpy.ndarray

In [96]:
x -= x

In [97]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [98]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [99]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print(f'result: {result}')

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


In [100]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.9322, 0.5823, 0.5336,  ..., 0.2467, 0.9016, 0.2830],
        [0.4273, 0.6575, 0.2838,  ..., 0.8618, 0.7298, 0.7482],
        [0.2847, 0.7286, 0.3775,  ..., 0.6659, 0.8316, 0.4436],
        ...,
        [0.4363, 0.8920, 0.4509,  ..., 0.4443, 0.3749, 0.8781],
        [0.1488, 0.8174, 0.5890,  ..., 0.9176, 0.1018, 0.0507],
        [0.7282, 0.5117, 0.0410,  ..., 0.9095, 0.7499, 0.7185]])

In [101]:
x.is_cuda

False

In [102]:
!nvidia-smi

Wed Oct  6 22:03:38 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8     2W /  N/A |    340MiB /  4096MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [103]:
x = x.cuda()

In [104]:
!nvidia-smi

Wed Oct  6 22:04:49 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8     2W /  N/A |    905MiB /  4096MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [105]:
x

tensor([[0.9322, 0.5823, 0.5336,  ..., 0.2467, 0.9016, 0.2830],
        [0.4273, 0.6575, 0.2838,  ..., 0.8618, 0.7298, 0.7482],
        [0.2847, 0.7286, 0.3775,  ..., 0.6659, 0.8316, 0.4436],
        ...,
        [0.4363, 0.8920, 0.4509,  ..., 0.4443, 0.3749, 0.8781],
        [0.1488, 0.8174, 0.5890,  ..., 0.9176, 0.1018, 0.0507],
        [0.7282, 0.5117, 0.0410,  ..., 0.9095, 0.7499, 0.7185]],
       device='cuda:0')

In [107]:
x = x.cpu()
!nvidia-smi

torch.cuda.empty_cache()
!nvidia-smi

Wed Oct  6 22:06:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8     3W /  N/A |    976MiB /  4096MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [108]:
device = torch.device('cuda:0')
x = x.to(device)
x

tensor([[0.9322, 0.5823, 0.5336,  ..., 0.2467, 0.9016, 0.2830],
        [0.4273, 0.6575, 0.2838,  ..., 0.8618, 0.7298, 0.7482],
        [0.2847, 0.7286, 0.3775,  ..., 0.6659, 0.8316, 0.4436],
        ...,
        [0.4363, 0.8920, 0.4509,  ..., 0.4443, 0.3749, 0.8781],
        [0.1488, 0.8174, 0.5890,  ..., 0.9176, 0.1018, 0.0507],
        [0.7282, 0.5117, 0.0410,  ..., 0.9095, 0.7499, 0.7185]],
       device='cuda:0')

In [110]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [111]:
c

tensor([[0.0272, 0.2901, 0.0476,  ..., 0.0376, 0.3210, 0.0789],
        [0.1913, 0.1225, 0.0138,  ..., 0.2958, 0.3774, 0.0424],
        [0.3235, 0.0571, 0.0567,  ..., 0.2898, 0.0086, 0.1096],
        ...,
        [0.3284, 0.0940, 0.2779,  ..., 0.5336, 0.1833, 0.2613],
        [0.2315, 0.0528, 0.1034,  ..., 0.3536, 0.8623, 0.3095],
        [0.3780, 0.4990, 0.0814,  ..., 0.6375, 0.7741, 0.1419]])

In [112]:
a

tensor([[0.2506, 0.6280, 0.0790,  ..., 0.1535, 0.3742, 0.1781],
        [0.5468, 0.4283, 0.0222,  ..., 0.8604, 0.4334, 0.0515],
        [0.5555, 0.3849, 0.5363,  ..., 0.4090, 0.0365, 0.3454],
        ...,
        [0.7057, 0.1287, 0.4334,  ..., 0.6890, 0.2034, 0.7010],
        [0.2913, 0.0998, 0.2242,  ..., 0.6884, 0.8901, 0.4623],
        [0.4273, 0.8341, 0.1974,  ..., 0.6996, 0.8203, 0.6748]])

In [113]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [114]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [116]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [117]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.7029, 1.4577, 1.4687, 1.2542, 1.7966],
         [1.3314, 1.7450, 1.2424, 1.4790, 1.1573],
         [1.0903, 1.2275, 1.5324, 1.3933, 1.1356],
         [1.2173, 1.6436, 1.9200, 1.9229, 1.8441],
         [1.7121, 1.8983, 1.7519, 1.4793, 1.1460]],

        [[1.7603, 1.7828, 1.9773, 1.4672, 1.5324],
         [1.8157, 1.6339, 1.0316, 1.3168, 1.8242],
         [1.8976, 1.8352, 1.1854, 1.9083, 1.9871],
         [1.7152, 1.3665, 1.2983, 1.0780, 1.8988],
         [1.2590, 1.8672, 1.9267, 1.9990, 1.2938]],

        [[1.4265, 1.1154, 1.3758, 1.9262, 1.1527],
         [1.1788, 1.3869, 1.3321, 1.0264, 1.6885],
         [1.9481, 1.3442, 1.7684, 1.1867, 1.8316],
         [1.6579, 1.2103, 1.5039, 1.5331, 1.4941],
         [1.8005, 1.2728, 1.5213, 1.2348, 1.7665]],

        [[1.0194, 1.3880, 1.2191, 1.7113, 1.2874],
         [1.0290, 1.2446, 1.4407, 1.5352, 1.7752],
         [1.1177, 1.6781, 1.7602, 1.9543, 1.9780],
         [1.8566, 1.1298, 1.7811, 1.8570, 1.3040],
         [1.5178, 1.1719,